include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    # Generated code
    - "**/translations*.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.gql.dart"
    - "**/*.g.dart"
    - "**/generated/**/*.dart"
    - "**/generated/*.dart"
    - "**/generated_plugin_registrant.dart"

  language:
    strict-raw-types: false

  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
    todo: ignore

linter:
  rules:
    sort_pub_dependencies: false
    prefer_relative_imports: true
    always_use_package_imports: false
    public_member_api_docs: false
    flutter_style_todos: false
